### ISSUE TITLE
Version mismatch lead to install error

### ISSUE THREAD

**Issue by vuanhson** [albertogeniola/ha-meross-local-broker#40]
Current version in github package: 0.0.1-alpha47
https://github.com/albertogeniola/ha-meross-local-broker/pkgs/container/aarch64-meross_local_broker

Version in config: 0.0.1-alpha48
https://github.com/albertogeniola/ha-meross-local-broker/blob/666dcaf4ddc4a7d221387866025f8e3d5fe89fc5/meross_local_broker/config.yaml#L2

Which lead to error: 
<img width="576" alt="Screenshot 2023-10-31 at 12 48 16" src="https://github.com/albertogeniola/ha-meross-local-broker/assets/6960172/c90efc45-66b7-41e2-bfb5-603097ef6820">
Please update the package or change in the config, thank you!

**Comment by fireheadman** [comment]
is it possible to install the older  alpha47 version?
I am getting this same issue....

**Comment by fireheadman** [comment]
Unable to install the add on to Supervised HA install

![image](https://github.com/albertogeniola/ha-meross-local-broker/assets/19847195/9a443cdd-6c56-4149-a983-622f6bfe8d25)
![image](https://github.com/albertogeniola/ha-meross-local-broker/assets/19847195/1ded1b6f-94fc-41e7-b420-2f5727a0523e)

**Comment by fireheadman** [comment]
not sure if this will help anyone... or maybe I even did something I shouldn't?
I forked this into my own github area, then edited the line mentioned by the OP to be 47 instead of 48.

deleted the original Addon Repo for this and added my github forked link instead.
Oddly enough it still shows up as Alberto's github, but it now installed fine and starts up, but is showing ver 47.

Maybe once this is corrected I can remove the addon and reinstall it from his github to catch the updates?
![image](https://github.com/albertogeniola/ha-meross-local-broker/assets/19847195/4a5a0af9-a78e-4bf8-b603-47021e724812)
![image](https://github.com/albertogeniola/ha-meross-local-broker/assets/19847195/eb553536-7367-4869-bda4-7a30215967f3)

**Comment by fireheadman** [comment]
other odd thing... the About shows no version
![image](https://github.com/albertogeniola/ha-meross-local-broker/assets/19847195/451d7a10-6d4f-4178-84e0-1dd29eb21170)

**Comment by albertogeniola** [comment]
Hi!

I am aware of it. I am working on a new version alpha49, which I hope I can release soon. That version will address the issue.

I'll keep you posted .

**Comment by albertogeniola** [comment]
Hi all,
a new version has just been published, and you should be able to download it any moment now ([just wait for the release pipeline to finish](https://github.com/albertogeniola/ha-meross-local-broker/actions/runs/6755843268)). Version **0.0.1-alpha49** should address some issues and fix them.

Some important points:
1. An attempt to avoid manual reconfiguration has been done, but won't cover all the cases out-there. You may need to re-configure the ADDON. If you get a "WRONG-CREDENTIALS" error, just re-configure the addon via the dedicated wizard and you should be good to go. The already configured devices should not be impacted.
2. The pairer app should be working, unless you log-out. If you log-out and the component has failed to update your passwords, you may need to re-configure the login credentials as per point 1.
3. I am planning to release a new version of the pairer app in the next days in order to improve it: I've realized there are a couple of frustrating bugs (i.e. IPv6 discovery not being correctly handled).

Please update to v0.0.1-alpha49 and report your experience here.

**Comment by albertogeniola** [comment]
Glad it solved the issue!
